version: '3.8'

volumes:
  local_postgres: {}

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: local_postgres
    volumes:
      - local_postgres:/var/lib/postgresql/data:Z
    env_file:
      - ../../.env
    ports:
      - '5432:5432'
